name = "lloydmoore-blog"
compatibility_date = "2024-09-23"
main = "src/index.js"
compatibility_flags = ["nodejs_compat"]

[build]
command = "hugo --gc --minify"

[assets]
directory = "./public"
binding = "ASSETS"

[vars]
ENVIRONMENT = "production"

# Remove email binding - using Resend API instead
# Environment variables are set in Cloudflare dashboard:
# RESEND_API_KEY = "re_..."

[observability.logs]
enabled = true

[env.preview.vars]
ENVIRONMENT = "preview"